export const emojieLibrary = [
  {
    Genre: 'Action',
    Emojie: '🧨',
    id: 1,
    GenreId: 28,
    isSelected: false,
  },
  {
    Genre: 'Adventure',
    Emojie: '💎',
    id: 2,
    GenreId: 12,
    isSelected: false,
  },
  {
    Genre: 'Animation',
    Emojie: '🦁',
    id: 3,
    GenreId: 16,
    isSelected: false,
  },
  {
    Genre: 'Comedy',
    Emojie: '🤣',
    id: 4,
    GenreId: 35,
    isSelected: false,
  },
  {
    Genre: 'Crime',
    Emojie: '🚔',
    id: 5,
    GenreId: 80,
    isSelected: false,
  },
  {
    Genre: 'Documentary',
    Emojie: '🎥',
    id: 6,
    GenreId: 99,
    isSelected: false,
  },
  {
    Genre: 'Drama',
    Emojie: '🎭',
    id: 7,
    GenreId: 18,
    isSelected: false,
  },
  {
    Genre: 'Family',
    Emojie: '👨‍👩‍👧',
    id: 8,
    GenreId: 10751,
    isSelected: false,
  },
  {
    Genre: 'Fantasy',
    Emojie: '🦄',
    id: 9,
    GenreId: 14,
    isSelected: false,
  },
  {
    Genre: 'History',
    Emojie: '⏳',
    id: 10,
    GenreId: 36,
    isSelected: false,
  },
  {
    Genre: 'Horror',
    Emojie: '🔪',
    id: 11,
    GenreId: 27,
    isSelected: false,
  },
  {
    Genre: 'Music',
    Emojie: '🎧',
    id: 12,
    GenreId: 10402,
    isSelected: false,
  },
  {
    Genre: 'Mystery',
    Emojie: '🔎',
    id: 13,
    GenreId: 9648,
    isSelected: false,
  },
  {
    Genre: 'Romance',
    Emojie: '😍',
    id: 14,
    GenreId: 10749,
    isSelected: false,
  },
  {
    Genre: 'Sci-Fi',
    Emojie: '👽',
    id: 15,
    GenreId: 878,
    isSelected: false,
  },
  {
    Genre: 'Thriller',
    Emojie: '😱',
    id: 16,
    GenreId: 53,
    isSelected: false,
  },
];
