POST http://localhost:8000/api/1.0/user/signup HTTP/1.1
content-type: application/json
    
    {
        "username": "Julian",
        "email": "Julian@web.de",
        "password": "123456"
    }

###

POST  http://localhost:8000 HTTP/1.1
content-type: application/json

    {
        "name": "John",
        "age": 30
    }

###

DELETE http://localhost:8000 HTTP/1.1


###
GET https://api.themoviedb.org/3/movie/now_playing?api_key=b83392e48747a4845ad80c2011eaa33b&language=en-US HTTP/1.1

###
GET http://localhost:8000/api/1.0/user/checkauth HTTP/1.1